[package]
name = "is_tested_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "is_tested_plugin"
path = "src/lib.rs"
plugin = true
crate-type = ["dylib"]

[dependencies]
